mango_sylius_ppl_parcelshop_return:
    path: /{_locale}/ppl/return-from-ppl/{methodCode}
    defaults:
        _controller: MangoSylius\SyliusPplParcelshopsPlugin\Controller\PplController::pplReturn
