parameters:
    pplShippingMethodsCodes: ['ppl_parcel_shop']
    mango_sylius_ppl_parcelshops_plugin_ppl_countries: ['cz', 'pl']

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    MangoSylius\SyliusPplParcelshopsPlugin\Form\Extension\ShipmentPplExtension:
        arguments:
            - '@sylius.shipping_methods_resolver'
            - '@sylius.repository.shipping_method'
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType

    MangoSylius\SyliusPplParcelshopsPlugin\Form\Extension\AdminPplShippingMethodExtension:
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodType
        arguments:
            $countryChoices: '%mango_sylius_ppl_parcelshops_plugin_ppl_countries%'

    MangoSylius\SyliusPplParcelshopsPlugin\Model\PplShipmentExporter:
        public: true
        arguments:
            $currencyConverter: '@sylius.currency_converter'
            $pplShippingMethodsCodes: '%pplShippingMethodsCodes%'
        tags:
            - name: mango_sylius.shipment_exporter_type
              type: 'ppl_parcel_shop'
              label: 'PPL ParcelShop'

    MangoSylius\SyliusPplParcelshopsPlugin\Controller\PplController:
        public: true
        arguments:
            $router: '@router'
            $shipmentRepository: '@sylius.repository.shipment'
            $cartContext: '@sylius.context.cart.composite'
            $flashBag: '@session.flash_bag'
            $translator: '@translator'
            $shippingMethodRepository: '@sylius.repository.shipping_method'
        tags:
            - 'controller.service_arguments'
